language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: e1whXuB5BoVbnRWNGnXtqTi1Ax8CzdSw0dRqz0es11zxM12cbMJzV/md825h1m4AgaqLY76ASAWfkLQZ+Y/4+hKOXvLn7+cXPt6HzkBXsOMNTTtoD/QcA8/47cXsjvy+y3Znzw4fkXk093x/wv21qrOL8lVCB0ESpBRKbp3oPcU39E8LASa/TZ1SK/zAsBVPP+eDgyKoUYc4sjxKDk8bASUFsU8pIXMC4tyjWzRvv3d49s1ay1hp+MZjyeZIBAcADoFqIDNrzTOxWq48yGK4Dfc/I/2japa6NQcDoDVZJZx+hZ+Golmup7XA+eOb/SgKMCFUV7CEmv/+lhTWNMfevICpmWR011vC1h+2cTHfOAJbwuYHlpwZKrb7au4zd3tPRgwZCV1Fglm13n94Fs9OzaXZY6s5QtxlhA03sy8GTwEJG5pIcdCdXNfulolaliypRWr1hddg1YsJ1d0CelcV0SRGCwtSOWgqS0P/fXn6XeO9LUEnialTdnhawlX6jYpOEkqedEsWD4lfNhybU8eIF3NnhQPKVO/aXUkzS7aL1tl6Pi332tGzcYbawJrL4DxmsONFucXOJVZMh/iOlMUHMuxCV23IZUJ44lPnKnFxFU+UnDcGDcTYn5bEZ5QX6IHcB46TxUs9dBfEWwuImpbuzwUjM8dVZiHz5A5rAd0dWDE=
  app: payday-assignment
  on:
    repo: xbexbex/Payday
